  - name: grab auth data from openstackrc for demo project
    shell: |
        source "{{ overcloudrc }}"
        echo "
        auth_url: $OS_AUTH_URL
        username: demo
        password: secrete
        project_name: demo
        domain_id: default
        "
    register: creds
  - set_fact:
      os_demo: "{{ creds.stdout | from_yaml }}"
        

